### ISSUE TITLE
Some questions about this paper.

### ISSUE THREAD

**Issue by eyuansu62** [NoviScl/AmbigPrompt#1]
Hi, its a great work and thanks for open-source code. I have some confusion and could you please give me some help.
1. In some cases, prompt-based interventions are more effective at steering the model than providing unambiguous demonstration examples. I do not find what the prompt-based interventions is from section 5.1.
2. While some interventions increase h2-accuracy, no intervention consistently gets the model to generalize according to the intended feature. what does the generalize mean here? It seems that there is no concept of generalization from context.

**Comment by NoviScl** [comment]
Hi, thanks for your interest!

1. "prompt-based intervention" here refers to the other steering methods we tried, like meaningful verbalizers, providing instructions or explanations. These are all trying to improve different components of the prompt design. 
2. "generalize" here basically means to adopt the alternative hypothesis (h2) in making predictions on the test examples.
